version: '3.8'

services:

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: caxa
      MYSQL_DATABASE: aulas1
      # MYSQL_USER: root
      # MYSQL_PASSWORD: caxa
    ports:
      - "3306:3306"  # Mapeamento da porta do MySQL
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  # Mapeamento da porta do Angular
    depends_on:
      - springboot
    networks:
      - app_network

  springboot:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Mapeamento da porta do Spring Boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aulas1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: caxa
    depends_on:
      - mysql
    networks:
      - app_network
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/api-carros-java-angular/nginx:/etc/nginx/nginx.conf
      - ./site:/usr/share/nginx/html
    depends_on:
      - angular
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
