version: '3.8'

services:

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: caxa
      MYSQL_DATABASE: aulas1
      MYSQL_USER: root
      MYSQL_PASSWORD: caxa
    ports:
      - "3306:3306"  # Mapeamento da porta do MySQL
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      bash -c "
        echo 'CREATE USER \"root\"@\"172.18.0.3\" IDENTIFIED BY \"caxa\";' &&
        echo 'GRANT ALL PRIVILEGES ON *.* TO \"root\"@\"172.18.0.3\";' &&
        echo 'FLUSH PRIVILEGES;' &&
        /entrypoint.sh mysqld
      "

  angular:
    image: node:14
    working_dir: /app
    volumes:
      - ./angular-app:/app
    ports:
      - "4200:4200"
    command: npm start

  springboot:
    image: openjdk:11
    working_dir: /app
    volumes:
      - ./springboot-app:/app
    ports:
      - "8080:8080"
    command: ./mvnw spring-boot:run

  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Corrigido o caminho para apontar diretamente para o arquivo nginx.conf
      - ./site:/usr/share/nginx/html
    depends_on:
      - angular
      - springboot
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
